### ISSUE TITLE
Login with HA not working

### ISSUE THREAD

**Issue by payano** [payano/homeassist-ng#6]
"Dear all,
Sorry but for me impossible to login in app...
Always the same message : password failed
and in home assistant server i view failed connexion frome mobile device.
idea ? need add someone in configuration ?
thank you for helping"

The way to make it work, enable trusted networks and add your ip range. without it, HomeAssist-ng does not get authenticated.
see: https://github.com/axzae/homeassist/issues/38

**Comment by arjanvroege** [comment]
I've only configured my LAN as trusted network, when starting the app it's connecting and right after the connection is made the app crashes on my Samsung Galaxy S7. Let me know if someone needs more information on this issue.

**Comment by lebaned** [comment]
Same issue here on my Wileyfox Swift 2X.

**Comment by payano** [comment]
If you have android studio and could run the app in debugger mode and send me the stacktrace from the console output, it would be very much appreciated. Otherwise I need some way to reproduce the bug.
Have you enabled websocket, can you provide your homeassistant and http section from configuration.yaml file.

**Comment by payano** [comment]
@lebaned, @arjanvroege : can you guys try if the application is working better now?
I need to refactor some code, but there is a working solution now. :)

**Comment by lebaned** [comment]
Yeah, I can login now. Thanks! :) But now when I try to add a widget made the app crashes. Tomorrow I will try to run the app in debugger mode inside Android Studio, but I've never done it before.

**Comment by payano** [comment]
If you are using the latest Home Assistant, the websocket api does not work, which HomeAssist-ng relies on, see: https://github.com/home-assistant/home-assistant/issues/19522
When doing the implementation for the new websocket class i got the message: {
  "id": 18,
  "type": "result",
  "success": false,
  "error": {
    "code": "unknown_error",
    "message": "Unknown error"
  }
}
i should get the response: "success": "true"
https://developers.home-assistant.io/docs/en/external_api_websocket.html

If you are on the latest HomeAssistant, try to downgrade to see if HomeAssist-ng works better.

**Comment by payano** [comment]
Is this still an issue, or could we close this?

**Comment by klaasnicolaas** [comment]
Think it is better to keep it open, until more people have done a debugger test

**Comment by lebaned** [comment]
I can login with a Long-Lived Access Token and control my entities from the app. I've tried to add a widget with HA version 0.83.3 and 0.84.4, but both times the app crashes. The debug logging inside Android Studio shows approximately the same error when I tab 'Select' at the 'Select Widget Control':
 
`D/YouQi: Widget onReceive
D/YouQi: Widget onUpdate
D/YouQi: Widget onUpdate appWidgetId: 770
D/YouQi: shit happend!
    Widget onReceive
D/YouQi: appWidgetIds [I@586a2ae ([I)
D/StrictMode: StrictMode policy violation; ~duration=11 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65599 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
        at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1042)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:843)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
        at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:259)
        at com.payano.homeassistant.provider.DatabaseManager.getConnections(DatabaseManager.java:388)
        at com.payano.homeassistant.provider.EntityWidgetProvider.onUpdate(EntityWidgetProvider.java:114)
        at android.appwidget.AppWidgetProvider.onReceive(AppWidgetProvider.java:66)
        at com.payano.homeassistant.provider.EntityWidgetProvider.onReceive(EntityWidgetProvider.java:159)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3190)
        at android.app.ActivityThread.-wrap17(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
    StrictMode policy violation; ~duration=5 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65599 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
        at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1042)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:843)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
        at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:259)
        at com.payano.homeassistant.provider.DatabaseManager.getWidgetById(DatabaseManager.java:516)
        at com.payano.homeassistant.provider.EntityWidgetProvider.onUpdate(EntityWidgetProvider.java:119)
        at android.appwidget.AppWidgetProvider.onReceive(AppWidgetProvider.java:66)
        at com.payano.homeassistant.provider.EntityWidgetProvider.onReceive(EntityWidgetProvider.java:159)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3190)
        at android.app.ActivityThread.-wrap17(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
D/StrictMode: StrictMode policy violation; ~duration=2147 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65599 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1440)
        at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1042)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:843)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
        at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:259)
        at com.payano.homeassistant.provider.DatabaseManager.getEntities(DatabaseManager.java:323)
        at com.payano.homeassistant.WidgetConfigActivity.initListViews(WidgetConfigActivity.java:81)
        at com.payano.homeassistant.WidgetConfigActivity.onCreate(WidgetConfigActivity.java:52)
        at android.app.Activity.performCreate(Activity.java:7023)
        at android.app.Activity.performCreate(Activity.java:7014)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
D/YouQi: Widget updateEntityWidget: {"appWidgetId":770,"attributes":{"brightness":76,"color_temp":454,"friendly_name":"Eettafel"},"checksum":"cba1a50997986ee468c27da56c75ae0e","entity_id":"light.eettafel","last_changed":"2018-12-27T20:55:00.265115+00:00","last_updated":"2018-12-27T20:55:00.265115+00:00","state":"on"}
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.payano.homeassistant, PID: 1468
    java.lang.IllegalArgumentException: No such package com.axzae.homeassistant
        at android.widget.RemoteViews.getApplicationInfo(RemoteViews.java:3853)
        at android.widget.RemoteViews.<init>(RemoteViews.java:2343)
        at com.payano.homeassistant.provider.EntityWidgetProvider.updateEntityWidget(EntityWidgetProvider.java:91)
        at com.payano.homeassistant.WidgetConfigActivity.performDone(WidgetConfigActivity.java:105)
        at com.payano.homeassistant.WidgetConfigActivity.onOptionsItemSelected(WidgetConfigActivity.java:69)
        at android.app.Activity.onMenuItemSelected(Activity.java:3464)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:380)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
        at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
        at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
        at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
        at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
        at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24774)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
I/zygote64: Do partial code cache collection, code=1006KB, data=597KB
I/zygote64: After code cache collection, code=1006KB, data=597KB
    Increasing code cache capacity to 3MB
W/CrashlyticsCore: Cannot send reports. Settings are unavailable.` 

But maybe we've to open another issue for this problem. Or doing I something wrong?

**Comment by payano** [comment]
@lebaned: thanks for the stacktrace! 
Usually the CrashlyticsCore sends stacktraces automatically, but somehow it didn’t work when your I application crashed.
I have removed com.axzae and replaced it with com.payano instead, and the stacktrace showed me that I have missed to change the package name in one file.
Can you please try to run the application now, I have not updated the application on google play yet, if the fix works, I will update google play.
Cheers!

**Comment by lebaned** [comment]
@payano: Adding widgets is now working, thanks! :)

**Comment by payano** [comment]
@klaasnicolaas , @lebaned , @arjanvroege: are you able to login, can I close this issue?

**Comment by arjanvroege** [comment]
It's working for me without any issues at the moment. 👍
